### ISSUE TITLE
better abstract notation?

### ISSUE THREAD

**Issue by jonsterling** [RedPRL/sml-typed-abts#13]
The current abstract notation is pretty noisy... To recap, a binder looks like this: `{u1,...,um}[x1,...,xn].M`. One thing we can do is have it so that when we don't bind any variables, we use `{u1,...,un}.M` and when we don't bind any symbols use use `[x1,...,xn].M`. But it's still a lot more noisy than before, with all the brackets!

Can anyone think of an unambiguous notation that isn't all bracket-y that we could use? I'd considered something like `u1,...,um | x1,...,xn. M`, but that's a little hard to read I think.

@freebroccolo @jozefg

**Comment by jonsterling** [comment]
(In the ABT paper, it's even more noisy than this, but we use this dope-looking double-struck lambda that makes up for it in coolness. In JonPRL proper, though, I'd like the notation to be clean and simple, and not look too alien.)

**Comment by ghost** [comment]
I think having sugar for the special cases like you describe is a good idea. I'm not sure about getting rid of the brackets entirely. My preference at this point would probably be to keep them but maybe make them optional for single variables. Maybe I would have a different opinion after looking at a large development though.

**Comment by jonsterling** [comment]
@freebroccolo Fair enough... Maybe it would be instructive for me to take a JonPRL development and see what it would look like. I worry a bit about the noise level, but maybe it wouldn't be that bad in practice.

**Comment by favonia** [comment]
Should we close this now?
