### ISSUE TITLE
add support for sml-open-ended

### ISSUE THREAD

**Issue by jonsterling** [RedPRL/sml-typed-abts#20]
~~(blocked on https://github.com/jonsterling/sml-open-ended/issues/1)~~

this should be analogous to https://github.com/jonsterling/sml-open-abt/. It can be implemented as a sub-library in this repository.

**Comment by jonsterling** [comment]
Hmmm! I actually wonder if this will be possible, since the type of operators is of higher kind.

**Comment by jonsterling** [comment]
I think that rather than try and figure this out, we may just go a different route and avoid the open-data-type jiggery-pokery in Red JonPRL.

For modularly defining & then composing operator signatures, this can be done manually:
1. Define your operator signatures, `A, B : OPERATOR`, with compatible arity structures.
2. Define another operator signature `O : OPERATOR` with constructors that inject `A,B` operators, and delegate to their implementations of the various operations.

It's really not so bad; the "fancy" approach was cool, but it was also very strange and hard to understand.

As for dynamically adding "fresh" operators in the course of interpreting a JonPRL development, one approach would be to just have a single dedicated operator for user-defined things, kind of like we did in the beginning (this is essentially what they do in Nuprl as well). I suppose I thought at the time that the "fresh" approach was better, but I'm not so sure anymore. @jozefg Do you have any thoughts on this? Do you remember if there was a real reason I switched things over, or if I just thought it was "cool" and wanted to try it?

**Comment by jozefg** [comment]
I'm OK with abondining open-ended, I seem to remember it being a "hey this is nifty" reason for switching and it was actually pretty slick, but it may simplify the usage of the ABT library in the refiner if everything user-defined is just stashed again in some `CUSTOM` constructor.. It gives us strictly more information in implementation if nothing else.

**Comment by jonsterling** [comment]
Yeah... Thinking about it again, I think that there was nothing wrong with using `CUSTOM` in the first place; it's essentially what they do in Nuprl (except that I believe that they don't have _any_ primitive operators except for `CUSTOM`).

If we had some kind of algebraic effects in SML like in the new OCaml stuff, we could do something really cool where `CUSTOM` doesn't need to carry around its own arity, but here, it will need to be annotated. (We can annotate it at parse-time by looking it up in the development context.)
