### ISSUE TITLE
remove AbtUtil

### ISSUE THREAD

**Issue by jonsterling** [RedPRL/sml-typed-abts#23]
`AbtUtil` is a strange little thing that might be useful for constructing deep ABTs in code, but this seems to be a kind of unlikely mode of use for the library (i.e. it just doesn't usually come up in practice).

The `AbtUtil` module also does something completely different from what it did in the CMU libraries, so it's possible people might get confused and think that they need to use it.

**Comment by jozefg** [comment]
This seems like a reasonable thing for me to accomplish tonight to get into this code :)

**Comment by jozefg** [comment]
Looking at this code, I can either
1. Lump this into ABT
2. Rename the module to be more directly named

Either of these seem reasonable but I think the first is less overhead. I would also suggest adding `outStar` for symmetry

**Comment by jonsterling** [comment]
do we even need this module? I thought it would be useful, but I haven't used it.

**Comment by jozefg** [comment]
Oh that's fair.. Yeah I can't think of a use..
