### ISSUE TITLE
[Example] Stepper for the Untyped Lambda Calculus?

### ISSUE THREAD

**Issue by markfarrell** [RedPRL/sml-typed-abts#31]
How would I implement a stepper for the untyped lambda calculus (with a strict, small step operational semantics) using this ABT library?

**Comment by jonsterling** [comment]
Great idea; we should provide this as an example, and maybe a few variations of it:
1. naïve small step w/ substitution
2. better small step w/ environments
3. even better small step (via abstract machine)

**Comment by markfarrell** [comment]
Hmm, could you give me some additional guidance on how to use your library? I'm still confused.

How would I go about declaring the sorts of terms of the untyped lambda calculus? Should I distinguish between expressions and values?

Would I then have to define my own (capture-avoidant) substitution function, or is the idea that the library can take care of that for me?

If the library takes care of that for me, how would I then use said substitution function inside the body of a small-step function?

How would I go about changing the sort of a term from expression to value when it reaches the form of a lambda term with no applications to be done (if I'm supposed to do that)?

**Comment by jonsterling** [comment]
@markfarrell It may depend on what particular lambda calculus you want to implement, but a nice example could be the "fine-grained call-by-value lambda calculus", which has a distinction between value & expression.
1. Sorts are declared by implementing the `SORT` signature.
2. The operators of the lambda calculus (like `lam`, `ap`, etc.) are defined in an implementation of the `OPERATOR` signature; in the case of this calculus, it will be easiest to implement the `SIMPLE_OPERATOR` signature and then put this through the `SimpleOperator` functor. In any case, each operator is assigned an _arity_ (described in PFPL).
3. Substitution is defined by the library without requiring any work from you.
4. Assuming you have used the `Abt` functor with your operator type to get a structure called (e.g.) `Tm : ABT`, then you can write `Tm.subst (m, x) n` to substitute the abt `m` for the free variable `x` in the abt `n`. There is also `Tm.substEnv` which is useful for substituting multiple variables whilst traversing the abt just once.

**Comment by jonsterling** [comment]
There are a few options for how you might implement the small step relation. One option is to say that the output of `step` is always of sort `exp`; that means that if you reach a value, you must wrap the value in the canonical injection of values into expressions (like `thunk`).

Another option is to make the output sort vary, such that sometimes the result of `step` is of sort `exp` and other times it is of sort `val`. I think that this last approach is not so elegant, and I would avoid it.

Separately, from the small step operational semantics you can define a big step natural semantics—and for this one, the input of `eval` will always be of sort `exp` and the output will always be of sort `val`.

**Comment by jonsterling** [comment]
@markfarrell By the way, I've just merged a branch that includes a new library for what's called "lazy computation systems". Basically, the idea is that you fragment the syntax into two categories: values and continuations. Continuations (which you can think of as "evaluation contexts" or "stack frames") would be things like `ap(M;–)` or `fst(–)`, etc.

Then, if you define how to plug a value into a continuation (like `lam(x.E[x])` plugs into `ap(M;–)` as `E[M]`), the library will give you for free a stepper based on an abstract machine (sort of like the stack machine in PFPL, but using environments/closures instead of naïve substitution).

This approach lets us get rid of a lot of the boilerplate associated with writing small-step interpreters, and will (hopefully, unless I've implemented it badly!) result in better performance.

**Comment by jonsterling** [comment]
@markfarrell There is an example here: https://github.com/RedPRL/sml-typed-abts/blob/master/example/lcs-playground.sml

Here's an example of stepping through the evaluation of a term (the notation is difficult to read, sorry):
![screen shot 2016-05-27 at 1 09 12 pm](https://cloud.githubusercontent.com/assets/55057/15624142/197e108a-2435-11e6-88c4-5d6f79a9e9e8.png)
