### ISSUE TITLE
Helper function makeApp looks wrong

### ISSUE THREAD

**Issue by wilcoxjay** [RedPRL/sml-typed-abts#73]
`makeApp` sets up an initial context [ctx0](https://github.com/RedPRL/sml-typed-abts/blob/daf36782a3ae25a14348492e6d372d49a6c4eb1b/src/core/abt.fun#L226) but then it's never used. 

This seems wrong, but I don't understand symbols well enough to know how to construct a failing test (either in the example in this repo or in RedPRL/sml-redprl).

I believe the fix is as simple as replacing the later use of `Ctx.empty` with `ctx0`, but I'd like a test to convince myself that this fixes things.

**Comment by jonsterling** [comment]
Yes, this definitely looks wrong... I will have to familiarize myself with this code again to see what it was supposed to do...

**Comment by jonsterling** [comment]
@wilcoxjay I believe that `makeApp` should be changed to have the following line:

``` sml
val ctx = Sp.foldr (fn (ABS (_, _, m), ctx) => Ctx.merge (ctx, getCtx m)) ctx0 es
```

What was supposed to happen here is that the free symbols/static variables of the _operator_ were supposed to be merged with those of its subterms.

**Comment by wilcoxjay** [comment]
Yes, that's what I thought originally, too. 

But now that I look at it again, it looks like the meaning of the context annotation at an application node is intended to _only_ contain those symbols of its subterms. For example, `symctx` takes the context annotation stored at the application node and adds in the support of the operator before returning it.

So it's clear that when accessing the symbol context, you want the union of the contexts of the subterms with the support of the operator. But the question is whether to store this in the context annotation when you build the application node or whether to add it in when you access it with `symctx`.

**Comment by jonsterling** [comment]
@wilcoxjay ah, very interesting... That would explain why the thing isn't broken everywhere.

Looking at the code, I think the most consistent thing to do is remove that dead line of code for now; ideally we should cache all that information eagerly, but I don't want to make that change without also changing the structure of the annotations. Ideally everything of type `abt` would be straightforwardly wrapped in an annotation, using some mutually recursive thing—but there is no need to make this change now.
